// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFav1iGQWEmbXv1XoELGf-mQ8RBqIZOMI',
    appId: '1:853439919740:web:ef515b39c3c5a0144a7bf9',
    messagingSenderId: '853439919740',
    projectId: 'autodoc-ai-89790',
    authDomain: 'autodoc-ai-89790.firebaseapp.com',
    storageBucket: 'autodoc-ai-89790.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkaavPSTgbSGS6O2s38g2eBp2oaNm8Di4',
    appId: '1:853439919740:android:9c86409bcca3ac6e4a7bf9',
    messagingSenderId: '853439919740',
    projectId: 'autodoc-ai-89790',
    storageBucket: 'autodoc-ai-89790.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM6Z9EKXWoJ3UlD6nIf4TGrSBK9Mglcvk',
    appId: '1:853439919740:ios:b8571f9dca4d34f14a7bf9',
    messagingSenderId: '853439919740',
    projectId: 'autodoc-ai-89790',
    storageBucket: 'autodoc-ai-89790.firebasestorage.app',
    iosBundleId: 'com.example.autodocAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBM6Z9EKXWoJ3UlD6nIf4TGrSBK9Mglcvk',
    appId: '1:853439919740:ios:b8571f9dca4d34f14a7bf9',
    messagingSenderId: '853439919740',
    projectId: 'autodoc-ai-89790',
    storageBucket: 'autodoc-ai-89790.firebasestorage.app',
    iosBundleId: 'com.example.autodocAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFav1iGQWEmbXv1XoELGf-mQ8RBqIZOMI',
    appId: '1:853439919740:web:626fdffd3b0e7f3d4a7bf9',
    messagingSenderId: '853439919740',
    projectId: 'autodoc-ai-89790',
    authDomain: 'autodoc-ai-89790.firebaseapp.com',
    storageBucket: 'autodoc-ai-89790.firebasestorage.app',
  );
}
